# Generated by Django 3.2.6 on 2021-10-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pernson_name', models.CharField(max_length=200)),
                ('appointment_date', models.DateTimeField(verbose_name='appointment date')),
                ('person_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.person')),
            ],
        ),
    ]
