# Generated by Django 3.2.6 on 2021-10-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='person_data',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pernson_name',
        ),
    ]
