# Generated by Django 3.2.6 on 2021-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20211003_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'FINISHED'), (2, 'CANCELED')], default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.IntegerField(choices=[(1, '08:00'), (2, '08:30'), (3, '09:00'), (4, '09:30'), (5, '10:00'), (6, '10:30'), (7, '11:00'), (8, '11:30'), (9, '12:00'), (10, '12:30'), (11, '13:00'), (12, '13:30'), (13, '14:00'), (14, '14:30'), (15, '15:00'), (16, '15:30'), (17, '16:00'), (18, '16:30'), (19, '17:00'), (20, '17:30'), (21, '18:00'), (22, '18:30'), (23, '19:00'), (24, '19:30'), (25, '20:00'), (26, '20:30'), (27, '21:00'), (28, '21:30'), (29, '22:00')], default=1),
        ),
    ]
